#pragma once

#include "Misc/EngineVersionComparison.h"

#define UE_VERSION_START(MajorVersion, MinorVersion, PatchVersion) \
UE_GREATER_SORT(ENGINE_MAJOR_VERSION, MajorVersion, UE_GREATER_SORT(ENGINE_MINOR_VERSION, MinorVersion, UE_GREATER_SORT(ENGINE_PATCH_VERSION, PatchVersion, true)))

#define UE_G_EDITOR_TRANS UE_VERSION_START(5, 1, 0)

#define UE_APP_STYLE_GET_BRUSH UE_VERSION_START(5, 1, 0)

#define UE_APP_STYLE_GET_MARGIN UE_VERSION_START(5, 1, 0)

#define UE_APP_STYLE_GET_FLOAT UE_VERSION_START(5, 1, 0)

#define UE_APP_STYLE_GET_FONT_STYLE UE_VERSION_START(5, 1, 0)

#define UE_APP_STYLE_GET_STYLE_SET_NAME UE_VERSION_START(5, 1, 0)

#define UE_ASSET_DATA_GET_ASSET_CLASS_STRING UE_VERSION_START(5, 1, 0)

#define UE_ASSET_DATA_GET_SOFT_OBJECT_PATH_STRING UE_VERSION_START(5, 1, 0)